import { join } from 'node:path';
import { homedir } from 'node:os';
import type { TildeConfig, DeveloperContext } from '../config/schema.js';

function expandTilde(p: string): string {
  if (p.startsWith('~/')) return join(homedir(), p.slice(2));
  return p;
}

export function generateGlobalGitconfig(config: TildeConfig): string {
  const dotfilesExpanded = expandTilde(config.dotfilesRepo);
  const lines: string[] = [
    '# Generated by tilde — do not edit manually',
    '# https://github.com/[user]/tilde',
    '',
    '[credential]',
    '\thelper = osxkeychain',
    '',
  ];

  for (const ctx of config.contexts) {
    const ctxPath = expandTilde(ctx.path);
    const gitconfigPath = join(dotfilesExpanded, 'git', `.gitconfig-${ctx.label}`);
    // gitdir: path must end with /
    lines.push(`[includeIf "gitdir:${ctxPath}/"]`);
    lines.push(`\tpath = ${gitconfigPath}`);
    lines.push('');
  }

  // Default identity (first context marked isDefault, or first context)
  const defaultCtx = config.contexts.find(c => c.isDefault) ?? config.contexts[0];
  if (defaultCtx) {
    lines.push('[user]');
    lines.push(`\tname = ${defaultCtx.git.name}`);
    lines.push(`\temail = ${defaultCtx.git.email}`);
    lines.push('');
  }

  return lines.join('\n');
}

export function generateContextGitconfig(context: DeveloperContext): string {
  const lines: string[] = [
    `# Generated by tilde for context: ${context.label}`,
    '',
    '[user]',
    `\tname = ${context.git.name}`,
    `\temail = ${context.git.email}`,
    '',
  ];

  if (context.authMethod === 'https') {
    lines.push('[credential]');
    lines.push('\thelper = osxkeychain');
    lines.push('');
  }

  return lines.join('\n');
}
