import type { TildeConfig } from '../config/schema.js';
import type { TildePlugin, VersionManagerPlugin, EnvLoaderPlugin } from '../plugins/api.js';

// Suppress unused import warning for EnvLoaderPlugin (used as type reference for plugin consumers)
export type { EnvLoaderPlugin };

const TILDE_MARKER_START = '# >>> tilde managed block';
const TILDE_MARKER_END = '# <<< tilde managed block';

function tiledBlock(label: string, content: string): string {
  return `${TILDE_MARKER_START}: ${label}\n${content}\n${TILDE_MARKER_END}: ${label}`;
}

export function generateBashProfile(config: TildeConfig, plugins: TildePlugin[]): string {
  const blocks: string[] = [
    '# Generated by tilde — do not edit the managed blocks manually',
    '# Manually added content below the managed blocks will be preserved',
    '',
  ];

  const versionManagerPlugins = plugins.filter(
    (p): p is VersionManagerPlugin => p.category === 'version-manager'
  );

  for (const vmPlugin of versionManagerPlugins) {
    const hook = vmPlugin.generateShellHook('bash');
    if (hook) {
      blocks.push(tiledBlock(`version-manager:${vmPlugin.id}`, hook));
      blocks.push('');
    }
  }

  if (config.configurations.direnv) {
    blocks.push(tiledBlock('direnv', 'eval "$(direnv hook bash)"'));
    blocks.push('');
  }

  const ghCliContexts = config.contexts.filter(c => c.authMethod === 'gh-cli');
  if (ghCliContexts.length > 0) {
    const cdCases = ghCliContexts
      .map(ctx => {
        const username = ctx.github?.username ?? '';
        if (!username) return null;
        const expandedPath = ctx.path.replace(/^~/, '$HOME');
        return `    ${expandedPath}*)\n      gh auth switch --user ${username} 2>/dev/null || true\n      ;;`;
      })
      .filter(Boolean)
      .join('\n');

    if (cdCases) {
      const cdHook = `function cd() {\n  builtin cd "$@" || return\n  case "$PWD" in\n${cdCases}\n  esac\n}`;
      blocks.push(tiledBlock('gh-cli-context-switch', cdHook));
      blocks.push('');
    }
  }

  if (config.configurations.aliases) {
    blocks.push(tiledBlock('aliases', '[[ -f ~/.aliases ]] && source ~/.aliases'));
    blocks.push('');
  }

  return blocks.join('\n');
}

export function generateFishConfig(config: TildeConfig, plugins: TildePlugin[]): string {
  const blocks: string[] = [
    '# Generated by tilde — do not edit the managed blocks manually',
    '# Manually added content below the managed blocks will be preserved',
    '',
  ];

  const versionManagerPlugins = plugins.filter(
    (p): p is VersionManagerPlugin => p.category === 'version-manager'
  );

  for (const vmPlugin of versionManagerPlugins) {
    const hook = vmPlugin.generateShellHook('fish');
    if (hook) {
      blocks.push(tiledBlock(`version-manager:${vmPlugin.id}`, hook));
      blocks.push('');
    }
  }

  if (config.configurations.direnv) {
    blocks.push(tiledBlock('direnv', 'direnv hook fish | source'));
    blocks.push('');
  }

  const ghCliContexts = config.contexts.filter(c => c.authMethod === 'gh-cli');
  if (ghCliContexts.length > 0) {
    const cdCases = ghCliContexts
      .map(ctx => {
        const username = ctx.github?.username ?? '';
        if (!username) return null;
        const expandedPath = ctx.path.replace(/^~/, '$HOME');
        return `    case "${expandedPath}*"\n      gh auth switch --user ${username} 2>/dev/null; or true`;
      })
      .filter(Boolean)
      .join('\n');

    if (cdCases) {
      const cdHook = `function cd\n  builtin cd $argv\n  switch $PWD\n${cdCases}\n  end\nend`;
      blocks.push(tiledBlock('gh-cli-context-switch', cdHook));
      blocks.push('');
    }
  }

  if (config.configurations.aliases) {
    blocks.push(tiledBlock('aliases', 'if test -f ~/.aliases; source ~/.aliases; end'));
    blocks.push('');
  }

  return blocks.join('\n');
}

export function generateZshrc(config: TildeConfig, plugins: TildePlugin[]): string {
  const blocks: string[] = [
    '# Generated by tilde — do not edit the managed blocks manually',
    '# Manually added content below the managed blocks will be preserved',
    '',
  ];

  // Version manager hooks
  const versionManagerPlugins = plugins.filter(
    (p): p is VersionManagerPlugin => p.category === 'version-manager'
  );

  for (const vmPlugin of versionManagerPlugins) {
    const hook = vmPlugin.generateShellHook('zsh');
    if (hook) {
      blocks.push(tiledBlock(`version-manager:${vmPlugin.id}`, hook));
      blocks.push('');
    }
  }

  // direnv hook
  if (config.configurations.direnv) {
    const direnvHook = 'eval "$(direnv hook zsh)"';
    blocks.push(tiledBlock('direnv', direnvHook));
    blocks.push('');
  }

  // gh-cli cd hook for context switching
  const ghCliContexts = config.contexts.filter(c => c.authMethod === 'gh-cli');
  if (ghCliContexts.length > 0) {
    const cdCases = ghCliContexts
      .map(ctx => {
        const username = ctx.github?.username ?? '';
        if (!username) return null;
        const expandedPath = ctx.path.replace(/^~/, '$HOME');
        return `    ${expandedPath}*)\n      gh auth switch --user ${username} 2>/dev/null || true\n      ;;`;
      })
      .filter(Boolean)
      .join('\n');

    if (cdCases) {
      const cdHook = `function cd() {\n  builtin cd "$@" || return\n  case "$PWD" in\n${cdCases}\n  esac\n}`;
      blocks.push(tiledBlock('gh-cli-context-switch', cdHook));
      blocks.push('');
    }
  }

  // Aliases source line
  if (config.configurations.aliases) {
    blocks.push(tiledBlock('aliases', '[[ -f ~/.aliases ]] && source ~/.aliases'));
    blocks.push('');
  }

  return blocks.join('\n');
}
