import type { EnvLoaderPlugin, SecretsBackendPlugin } from '../../api.js';
import { run } from '../../../utils/exec.js';
import { PluginError } from '../../api.js';
import homebrewPlugin from '../homebrew/index.js';
import type { DeveloperContext } from '../../../config/schema.js';

class DirenvPlugin implements EnvLoaderPlugin {
  readonly id = 'direnv';
  readonly name = 'direnv';
  readonly version = '1.0.0';
  readonly category = 'env-loader' as const;
  readonly source = 'first-party' as const;
  readonly supportedPlatforms = ['darwin', 'linux'] as const;

  async isAvailable(): Promise<boolean> {
    try {
      await run('direnv', ['version']);
      return true;
    } catch {
      return false;
    }
  }

  async install(): Promise<void> {
    try {
      const result = await homebrewPlugin.installPackages(['direnv']);
      if (result.failed.length > 0) {
        throw new PluginError(this.id, 'Failed to install direnv via Homebrew', 'INSTALL_FAILED');
      }
    } catch (err) {
      if (err instanceof PluginError) throw err;
      throw new PluginError(this.id, 'Failed to install direnv', 'INSTALL_FAILED', err as Error);
    }
  }

  generateEnvrc(opts: {
    context?: DeveloperContext;
    envVars: Array<{ key: string; value: string }>;
    secretsBackend: SecretsBackendPlugin;
  }): string {
    const lines: string[] = [
      '# Generated by tilde — do not edit manually',
      '# https://direnv.net',
      '',
    ];

    // Add runtime init if secrets backend requires it
    const initCode = opts.secretsBackend.getRuntimeInitCode?.();
    if (initCode) {
      lines.push('# Secrets backend initialization');
      lines.push(initCode);
      lines.push('');
    }

    // Git identity exports from context
    if (opts.context?.git) {
      lines.push('# Git identity');
      lines.push(`export GIT_AUTHOR_NAME="${opts.context.git.name}"`);
      lines.push(`export GIT_AUTHOR_EMAIL="${opts.context.git.email}"`);
      lines.push(`export GIT_COMMITTER_NAME="${opts.context.git.name}"`);
      lines.push(`export GIT_COMMITTER_EMAIL="${opts.context.git.email}"`);
      lines.push('');
    }

    if (opts.envVars.length > 0) {
      lines.push('# Environment variables (backend references)');
      for (const { key, value } of opts.envVars) {
        lines.push(`export ${key}="${value}"`);
      }
    }

    return lines.join('\n') + '\n';
  }

  generateShellHook(shell: 'zsh' | 'bash' | 'fish'): string {
    switch (shell) {
      case 'zsh':
        return 'eval "$(direnv hook zsh)"';
      case 'bash':
        return 'eval "$(direnv hook bash)"';
      case 'fish':
        return 'direnv hook fish | source';
    }
  }
}

export default new DirenvPlugin();
